### PR TITLE
Added sample models for Draco_mesh_compression_extension

### PR DESCRIPTION
**Pull request by fanzhanggoogle**
Hi,

This PR adds sample models for usage of [KHR_draco_geometry_compression](https://github.com/KhronosGroup/glTF/pull/874). These models are created using [COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF/pull/79). Please see the `glTF-Draco` folder in each model folder. The models could be loaded by modified [ThreeJS GLTF loader](https://github.com/fanzhanggoogle/gltf-test/tree/draco_2.0_1.0/libs/three.js/draco).

Here's preliminary compression result on the meshes of sample models:
### Comparison on geometries (mesh/primitive only)
| Model Name | Total Geometry Size (byte) | Compressed Size (byte) | Compression Ratio |
| ------------- | ------------- | ------------- | ------------- |
| 2CylinderEngine  | 1794612 | 183530 | 9.778303275 |
| Box | 648  | 160 | 4.05 | 
| BrainStem | 2009628 | 167491 | 11.9984 | 
| Buggy  | 7745988  | 692824 | 11.18031131 | 
| CesiumMan  | 211320  | 17535 | 12.05132592 | 
| CesiumMilkTruck  | 108144  | 14785 | 7.31444 | 
| Duck  | 102040  | 11354 | 8.987141096 | 
| GearboxAssy  | 4915704  | 423307 | 11.61262157 | 
| Monster  | 48984  | 6664 | 7.350540216 | 
| ReciprocatingSaw  | 3496764 | 333415 | 10.48772251 | 
| RiggedFigure  | 19296  | 2830 | 6.81837 | 
| RiggedSimple  | 5736  | 772 | 7.430051813 | 
| VC  | 669786  | 152188 | 4.401043 | 

### Comparison on glTF files (including texture, gltf file and other data)
| Model Name | Uncompressed GLB File Size  (byte) | Compressed GLB File Size (byte) | Compression Ratio |
| ------------- | ------------- | ------------- | ------------- |
| 2CylinderEngine  | 1838084 | 230056 | 7.989724241 |
| Box | 1664  | 1240 | 1.341935484 | 
| BrainStem | 3195280 | 1357816 | 2.35324963 | 
| Buggy  | 7885636  | 845776 | 9.323551389 | 
| CesiumMan  | 491700  | 297696 | 1.65168494 | 
| CesiumMilkTruck  | 542172  | 449056 | 1.207359438 | 
| Duck  | 120484  | 29768 | 4.047433486 | 
| GearboxAssy  | 4958788  | 470248 | 10.54504857 | 
| Monster  | 327700  | 285204 | 1.149002118 | 
| ReciprocatingSaw  | 3562996 | 405476 | 8.787193323 | 
| RiggedFigure  | 50092  | 33416 | 1.499042375 | 
| RiggedSimple  | 11072  | 6004 | 1.844103931 | 
| VC  | 3086448  | 2584244 | 1.194333043 | 

For geometry part of data, the extension has a good compression ratio around 9X in average. But we are aware of that if comparing the entire glTF assets, the sizes of some models don't have significant reduction. That's mainly because the animation data or texture image is a big part of the asset which the extension doesn't compress.

@lexaknyazev
@FrankGalligan
@jbrettle
@ondys
@pjcozzi

### CODE REVIEW

**Comment by pjcozzi** [comment]
@fanzhanggoogle did you mean to close this?

**Comment by pjcozzi** [comment]
Or did you mean to open this into the Khronos repo?

**Comment by fanzhanggoogle** [comment]
Hi @pjcozzi , Yes. I have prepared the models but I think it's better to wait for the ratification to be done before making a PR to the Khronos repo?

**Comment by pjcozzi** [comment]
Perhaps at least open the pull request to encourage early adopters?

**Comment by fanzhanggoogle** [comment]
@pjcozzi Sounds good. Opened the PR. Thanks!

**Pull request closed without merging**
